spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

github.webhook.secret=${GITHUB_WEBHOOK_SECRET}

github.api.token=${GITHUB_API_TOKEN}
github.api.base-url=https://api.github.com
github.api.connect-timeout-ms=${GITHUB_API_CONNECT_TIMEOUT_MS}
github.api.read-timeout-ms=${GITHUB_API_READ_TIMEOUT_MS}

management.endpoints.web.exposure.include=*